### Create a new category
POST http://localhost:4000/api/categories
Content-Type: application/json

{
  "name": "Science-Fiction"
}

### Create a new movie
POST http://localhost:4000/api/movies
Content-Type: application/json

{
  "title": "Titanic",
  "picture": "http://example.com/Titanic.jpg",
  "category_id": 2
}

### Get movies from a category
GET http://localhost:4000/api/categories/3/movies

### Create a new performer
POST http://localhost:4000/api/performers
Content-Type: application/json

{
  "name": "Kate Winslet"
}

### Associate a performer to a movie
PUT http://localhost:4000/api/movies/7/performers/2

### Get all performers in a movie
GET http://localhost:4000/api/movies/7/performers